// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/phpboyscout/go/errorhandling"
)

// NewMockErrorHandler creates a new instance of MockErrorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorHandler {
	mock := &MockErrorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockErrorHandler is an autogenerated mock type for the ErrorHandler type
type MockErrorHandler struct {
	mock.Mock
}

type MockErrorHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorHandler) EXPECT() *MockErrorHandler_Expecter {
	return &MockErrorHandler_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type MockErrorHandler
func (_mock *MockErrorHandler) Error(ctx context.Context, err error, opts ...errorhandling.ReportOption) {
	if len(opts) > 0 {
		_mock.Called(ctx, err, opts)
	} else {
		_mock.Called(ctx, err)
	}

	return
}

// MockErrorHandler_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockErrorHandler_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - ctx context.Context
//   - err error
//   - opts ...errorhandling.ReportOption
func (_e *MockErrorHandler_Expecter) Error(ctx any, err any, opts ...any) *MockErrorHandler_Error_Call {
	return &MockErrorHandler_Error_Call{Call: _e.mock.On("Error",
		append([]any{ctx, err}, opts...)...)}
}

func (_c *MockErrorHandler_Error_Call) Run(run func(ctx context.Context, err error, opts ...errorhandling.ReportOption)) *MockErrorHandler_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		var arg2 []errorhandling.ReportOption
		var variadicArgs []errorhandling.ReportOption
		if len(args) > 2 {
			variadicArgs = args[2].([]errorhandling.ReportOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockErrorHandler_Error_Call) Return() *MockErrorHandler_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorHandler_Error_Call) RunAndReturn(run func(ctx context.Context, err error, opts ...errorhandling.ReportOption)) *MockErrorHandler_Error_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function for the type MockErrorHandler
func (_mock *MockErrorHandler) Fatal(ctx context.Context, err error, opts ...errorhandling.ReportOption) int {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, err, opts)
	} else {
		tmpRet = _mock.Called(ctx, err)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Fatal")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(context.Context, error, ...errorhandling.ReportOption) int); ok {
		r0 = returnFunc(ctx, err, opts...)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockErrorHandler_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockErrorHandler_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - ctx context.Context
//   - err error
//   - opts ...errorhandling.ReportOption
func (_e *MockErrorHandler_Expecter) Fatal(ctx any, err any, opts ...any) *MockErrorHandler_Fatal_Call {
	return &MockErrorHandler_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]any{ctx, err}, opts...)...)}
}

func (_c *MockErrorHandler_Fatal_Call) Run(run func(ctx context.Context, err error, opts ...errorhandling.ReportOption)) *MockErrorHandler_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		var arg2 []errorhandling.ReportOption
		var variadicArgs []errorhandling.ReportOption
		if len(args) > 2 {
			variadicArgs = args[2].([]errorhandling.ReportOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockErrorHandler_Fatal_Call) Return(n int) *MockErrorHandler_Fatal_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockErrorHandler_Fatal_Call) RunAndReturn(run func(ctx context.Context, err error, opts ...errorhandling.ReportOption) int) *MockErrorHandler_Fatal_Call {
	_c.Call.Return(run)
	return _c
}

// SetUsage provides a mock function for the type MockErrorHandler
func (_mock *MockErrorHandler) SetUsage(usage func() error) {
	_mock.Called(usage)
	return
}

// MockErrorHandler_SetUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUsage'
type MockErrorHandler_SetUsage_Call struct {
	*mock.Call
}

// SetUsage is a helper method to define mock.On call
//   - usage func() error
func (_e *MockErrorHandler_Expecter) SetUsage(usage any) *MockErrorHandler_SetUsage_Call {
	return &MockErrorHandler_SetUsage_Call{Call: _e.mock.On("SetUsage", usage)}
}

func (_c *MockErrorHandler_SetUsage_Call) Run(run func(usage func() error)) *MockErrorHandler_SetUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func() error
		if args[0] != nil {
			arg0 = args[0].(func() error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockErrorHandler_SetUsage_Call) Return() *MockErrorHandler_SetUsage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorHandler_SetUsage_Call) RunAndReturn(run func(usage func() error)) *MockErrorHandler_SetUsage_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockErrorHandler
func (_mock *MockErrorHandler) Warn(ctx context.Context, err error, opts ...errorhandling.ReportOption) {
	if len(opts) > 0 {
		_mock.Called(ctx, err, opts)
	} else {
		_mock.Called(ctx, err)
	}

	return
}

// MockErrorHandler_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockErrorHandler_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - ctx context.Context
//   - err error
//   - opts ...errorhandling.ReportOption
func (_e *MockErrorHandler_Expecter) Warn(ctx any, err any, opts ...any) *MockErrorHandler_Warn_Call {
	return &MockErrorHandler_Warn_Call{Call: _e.mock.On("Warn",
		append([]any{ctx, err}, opts...)...)}
}

func (_c *MockErrorHandler_Warn_Call) Run(run func(ctx context.Context, err error, opts ...errorhandling.ReportOption)) *MockErrorHandler_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		var arg2 []errorhandling.ReportOption
		var variadicArgs []errorhandling.ReportOption
		if len(args) > 2 {
			variadicArgs = args[2].([]errorhandling.ReportOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockErrorHandler_Warn_Call) Return() *MockErrorHandler_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorHandler_Warn_Call) RunAndReturn(run func(ctx context.Context, err error, opts ...errorhandling.ReportOption)) *MockErrorHandler_Warn_Call {
	_c.Run(run)
	return _c
}
